equipo:
    path:     /
    defaults: { _controller: "AcmeSicopeBundle:Equipo:index" }

equipo_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeSicopeBundle:Equipo:show" }

equipo_new:
    path:     /new
    defaults: { _controller: "AcmeSicopeBundle:Equipo:new" }

equipo_create:
    path:     /create
    defaults: { _controller: "AcmeSicopeBundle:Equipo:create" }
    requirements: { _method: post }

equipo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeSicopeBundle:Equipo:edit" }

equipo_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeSicopeBundle:Equipo:update" }
    requirements: { _method: post|put }

equipo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeSicopeBundle:Equipo:delete" }
    requirements: { _method: post|delete }
